# -*- coding: utf-8 -*-
"""IRIS_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18SQT3DS6eFSAzvE_WtugEnfsMLOgINqp
"""

!pip install fastapi uvicorn

from fastapi import FastAPI
from pydantic import BaseModel
import joblib
import pandas as pd

app = FastAPI()

from google.colab import drive
drive.mount('/content/drive')

# Load the trained model
model = joblib.load('/content/drive/MyDrive/AI BootCamp/iris_model.pkl')

# Define the input data structure
class IrisData(BaseModel):
    sepal_length: float
    sepal_width: float
    petal_length: float
    petal_width: float

# Define the prediction endpoint
@app.post('/predict')
def predict(data: IrisData):
    # Convert input data to a DataFrame
    df = pd.DataFrame([data.dict().values()], columns=data.dict().keys())

    # Make a prediction
    prediction = model.predict(df)

    # Return the prediction
    return {'prediction': int(prediction[0])}

