# -*- coding: utf-8 -*-
"""IRIS_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cZsLby980nHlcxKs2k-imRacUzU-QfqW
"""

!pip install gradio streamlit

import gradio as gr
import requests
import joblib

# Define the function to interact with the FastAPI endpoint
def predict_iris(sepal_length, sepal_width, petal_length, petal_width):
    response = requests.post(
        'http://127.0.0.1:8000/predict',
        json={
            'sepal_length': sepal_length,
            'sepal_width': sepal_width,
            'petal_length': petal_length,
            'petal_width': petal_width
        }
    )
    return response.json()['prediction']

# Create the Gradio interface
interface = gr.Interface(
    fn=predict_iris,
    inputs=[
        gr.Number(label="Sepal Length"),
        gr.Number(label="Sepal Width"),
        gr.Number(label="Petal Length"),
        gr.Number(label="Petal Width")
    ],
    outputs="text",
    title="Iris Species Predictor"
)

# Launch the interface
interface.launch()